### ISSUE TITLE
Dataset Structure updated

### ISSUE THREAD

**Issue by Roboticyang** [beapc18/AffordanceNet#1]
Hello @beapc18,

I am trying to re-train your re-implementation of AffordanceNet model. After a few trials that I have noticed that you are using the VOC2012 dataset structures/xml files. I have update the dataset folders as the code setup.

However, I see the annotation files are all in xml format. The IIT dataset come with txt files for both bounding boxes and masks. I am wondering if you could share a sample dataset bbox and mask with us, so we can try to convert them ourselves.

Beside above request, I am wondering if there is any other modifications on the dataset?

Thanks!

**Comment by beapc18** [comment]
Hi @Roboticyang,
You have to follow the instructions in the training section here https://github.com/nqanh/affordance-net .
They have a link to download the formatted dataset, including xml annotations.
I have used the dataset that is downloaded from that link without any further modifications.
